### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by UniquePanda** [pointcloudtechnology/resumable.js#9]
After #5, #6, and #7 the readme should be updated to reflect the changes we made to the package.

**Comment by williamdes** [comment]
Thank you so much for taking back maintenance on this JS library !
I am now finishing my 2021 project on porting the PHP back end to something clean: https://github.com/code-lts/resumable.php
This library saved it

**Comment by williamdes** [comment]
Should we request: resumable.js.org ? from https://js.org/

Rather than fighting and losing money on the old lost domain lost to robots: resumable.js

**Comment by UniquePanda** [comment]
> Should we request: resumable.js.org ? from https://js.org/
> 
> Rather than fighting and losing money on the old lost domain lost to robots: resumable.js

Hm, interesting idea.
For now it's unlikely that we can find the time to additionally maintain a website for the project.
However, in case we'll ever have some hours to spare, we could reconsider this. I'll move it into an own issue. 🙂
